#pragma once

#include <glad/glad.h>

#include <string>

namespace Marlin {
    class Shader {
        public:
            unsigned int ID;

            // Compiles and links shaders. Param strings expected to be generated by xxd
            Shader(const char* vertexSource, const char* fragmentSource);

            // Activate shader
            void use();

            // Utility Uniform functions
            void setBool(const std::string &name, bool value) const;
            void setInt(const std::string &name, int value) const; 
            void setFloat(const std::string &name, float value) const;

    };
}